# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-us'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /blog/

# Website info
title: bmanohar's blog
name: Balakumaran Manoharan
description: Data Science, Machine Learning, Artificial Intelligence, Data Visualization
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
url: https://bmanohar16.github.io
production_url: https://bmanohar16.github.io/blog/
source_url: https://github.com/bmanohar16/blog/

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: bmanohar16_ # replace by your username
github: bmanohar16 # replace by your username

# Disqus
disqus: True
disqus_shortname: bmanohar16 # replace with your disqus username

# Google Analytics
google_analytics: UA-123056660-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed]

rss: True
author: bmanohar16

feed:
  path: feed.xml

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: bmanohar16
repo: blog
branch: master
relative_source: ../blog/
destination: ../gh-pages/
production_url:  https://bmanohar16.github.io/blog/
source_url:  https://github.com/bmanohar16/blog/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
  - yarn.lock
